- hosts: all
  become: yes
  tasks:
  - name: Remove pacotes antigos
    package:
      name: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']
      state: absent
  - name: Instalacao de dependencias em distro Debian/Ubuntu
    block:
    - name: Download da chave do repositório
      apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
        state: present
    - name: Configurar repositório
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker-ce
    - name: Instalar dependências
      package:
        name: ['apt-transport-https', 'ca-certificates', 'gnupg-agent', 'software-properties-common']
        state: present
    when: ansible_distribution|lower == 'debian' or ansible_distribution|lower == 'ubuntu' 
  - name: Instalacao no CentOS/RHEL
    block:
    - name: Download da chave do repositório
      rpm_key:
        state: present
        key: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
    - name: Configurar repositório
      yum_repository:
        name: docker-ce
        baseurl: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/$releasever/$basearch/stable"
        description: Docker CE Stable
        file: docker-ce
    when: ansible_distribution|lower == 'centos' or ansible_distribution|lower == 'rhel'
  - name: Instalar pacote docker-ce
    package:
      name: docker-ce
      state: present
  - name: Adiciona servico docker na inicializacao automatica
    service:
      name: docker
      enabled: yes
      state: started
  - name: Instala docker-compose
    get_url:
      url: "https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
      dest: /usr/bin/docker-compose
      mode: '0755'
